# Workflow to ensure whenever a Github PR is submitted, 
# a JIRA ticket gets created automatically. 
name: docker-image

# Controls when the action will run. 
on:
  # Triggers the workflow on pull request events but only for the master branch
  pull_request_target:
    types: [opened, reopened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-container:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build the docker image
        working-directory: udagram-api-feed
        run: docker build . --file Dockerfile --tag udagram-api-feed:$(date +%s)
      - name: Build the docker image
        working-directory: udagram-api-user
        run: docker build . --file Dockerfile --tag udagram-api-user:$(date +%s)
      - name: Build the docker image
        working-directory: udagram-frontend
        run: docker build . --file Dockerfile --tag udagram-frontend:$(date +%s)
      - name: Build the docker image
        working-directory: udagram-reverseproxy
        run: docker build . --file Dockerfile --tag udagram-reverseproxy:$(date +%s)