# Workflow to ensure whenever a Github PR is submitted, 
# a JIRA ticket gets created automatically. 
name: docker-image

# Controls when the action will run. 
on:
  # Triggers the workflow on pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build & Push docker image
        working-directory: udagram-api-feed
        run: | 
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "heniarmoniyem" --password-stdin
          docker build . --file Dockerfile --tag udagram-api-feed:v1
          docker push heniarmoniyem/udagram-api-feed
      - name: Build & Push docker image 
        working-directory: udagram-api-user
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "heniarmoniyem" --password-stdin
          docker build . --file Dockerfile --tag udagram-api-user:v1
          docker push heniarmoniyem/udagram-api-user
      - name: Build & Push docker image 
        working-directory: udagram-frontend 
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "heniarmoniyem" --password-stdin
          docker build .--file Dockerfile --tag udagram-frontend:v1
          docker push heniarmoniyem/udagram-frontend
      - name: Build & Push docker image 
        working-directory: udagram-reverseproxy
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "heniarmoniyem" --password-stdin
          docker build . --file Dockerfile --tag udagram-reverseproxy:v1 
          docker push heniarmoniyem/udagram-reverseproxy